### ISSUE TITLE
 Creating a ReadOnly view of buffer must copy data to new buffer

### ISSUE THREAD

**Issue by jridgewell** [tc39/proposal-limited-arraybuffer#6]
This must copy the data into a new readonly array buffer. For the data properties to be truly readonly, they must be frozen with non-configurable, non-writable descriptors, so the `Object.getOwnPropertyDescriptor(typedarray, '0')` must have `{ configurable: false, writeable: false }` (and a data value). However, if the readonly view of the underlying `buffer` shared the same memory, the data property could be changed by the original readwrite buffer:

```js
const readwrite = new Uint8Array(1);
assert.equal(readwrite[0], 0);
assert.equal(Object.getOwnPropertyDescriptor(readwrite, '0').configurable, true);
assert.equal(Object.getOwnPropertyDescriptor(readwrite, '0').writable, true);

const readonly = new Uint8Array(array.buffer, { readonly: true });
assert.equal(readonly[0], 0);
assert.equal(Object.getOwnPropertyDescriptor(readonly, '0').configurable, false);
assert.equal(Object.getOwnPropertyDescriptor(readonly, '0').writable, false);

// This cannot change the readonly data, per the proxy invariants
readwrite[0] = 1;

// This data property must always report `value === 0`, per the proxy invariants
assert.equal(readonly[0], 0);
```

This just means the underlying buffer must be copied to a new readonly buffer, and isn't just a "view" of the underlying data.

**Comment by Jack-Works** [comment]
So the read-only view to a read-write buffer is a _feature_ (at least I want it to be).
The object descriptor part is interesting. I think we can make it like an exported item on the module namespace object. Non configurable, writeable but throw Type Error on external write.

![image](https://user-images.githubusercontent.com/5390719/113658982-aecf0200-96d3-11eb-849d-a480246153fb.png)

This behavior also applies to the read-only view to a read-write buffer without copying all data or violate the proxy invariants

**Comment by CrimsonCodes0** [comment]
On top of having to copy the internal buffer's data, there is no way that this proposal could work with the Records and Tuples proposal, as the TypedArrays are objects, in particular, objects with *mutable prototypes*.

I believe that these would need to be their own classes, separate from %TypedArray%, but I am not sure.

**Comment by Jack-Works** [comment]
Maybe we can add a (set of?) new primitive types that mapped to immutable binary data.

Let's call it "primitive binary" for now.

Since _primitive binary_ is a primitive value, it _is_ immutable and works with R&T.
A new _primitive binary_ should be created from an existing ArrayBuffer (since there is no way to represent binary data in the syntax level).

```js
const bin = buffer.toPrimitive()
typeof bin === "binary"

const x = #{ data: bin } // OK
```

If the ArrayBuffer is frozen, the engine can safely share the same memory between the frozen buffer and the primitive data. Otherwise, it has to copy the whole buffer beside the scene.

**Comment by Jack-Works** [comment]
Covered in new API design (#13). If anything is not covered, please let me know!
